### create product
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "sku": "SKU-001",
  "name": "Producto de prueba",
  "price": 19.99
}


### Get paged products
GET http://localhost:8080/api/v1/products?page=0&size=10

### Get product by id
GET http://localhost:8080/api/v1/products/1
### Get product by id (error test)
GET http://localhost:8080/api/v1/products/21
